# Generated by Django 6.0.3 on 2026-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('venue_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('estimated_cost', models.CharField(max_length=100)),
                ('why_it_fits', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
